name: Build Artifact (All Branches Except Master)

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:  # Allow manual runs if needed

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR using Maven
        run: mvn clean package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: erp-backend
          path: target/*.jar
