name: Maven Package & Docker Push

on:
  push:
    branches: ['**']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t tanishq2208/erp:latest .

    - name: Push Docker Image (latest)
      run: docker push tanishq2208/erp:latest

    - name: Tag & Push Docker Image with Release Tag
      if: github.event_name == 'release'
      run: |
        docker tag tanishq2208/erp:latest tanishq2208/erp:${{ github.event.release.tag_name }}
        docker push tanishq2208/erp:${{ github.event.release.tag_name }}
